root: true
env:
  browser: true
  jest: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - dist
  - node_modules
  - src/coverage
rules: {}
