root: true
env:
  browser: true
  es2021: true
  jest: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - dist
  - node_modules
  - src/coverage
rules:
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-empty-function':
    - error
    - allow: [constructors]
